### ISSUE TITLE
Bugfix: remove stray debug statement

### ISSUE THREAD

**Issue by webketje** [metalsmith/sass#2]
On [lib/index.js#L62](https://github.com/metalsmith/sass/blob/master/lib/index.js#L62) there is a stray debug statement that needs to be removed. Furthermore the `%o` in [lib/index.js#L74](https://github.com/metalsmith/sass/blob/master/lib/index.js#L74) should be `%O` (capitals)

**Comment by PreetSangha** [comment]
I've created a pr for your review https://github.com/metalsmith/sass/pull/3. I'm still new to this so am not sure if I've done everything correctly. Please could you let me know if you need me to correct it.

**Comment by webketje** [comment]
@PreetSangha yes thank you. Can you add this? 
> Furthermore the %o in [lib/index.js#L74](https://github.com/metalsmith/sass/blob/master/lib/index.js#L74) should be %O (capitals)

You can re-use the same commit by updating the file & doing `git add lib/index.js && git commit --amend`, followed by `git push --force origin`

**Comment by PreetSangha** [comment]
@webketje Thank you for your response. I've updated #3  for your review. Please don't hesitate to come back to me to correct it further.
