### ISSUE TITLE
Error metalsmith.match is not a function when loaded using metalsmith-sugar

### ISSUE THREAD

**Issue by depuits** [metalsmith/sass#4]
I'm not sure if this is an issue of this plugin or the metalsmith-sugar plugin but this is the first plugin which is giving me trouble.

So when loading this using following code

    var sugar = require('metalsmith-sugar')();
    sugar
	    .use('@metalsmith/sass', {
		    loadPaths: ['node_modules'],
		    entries: {
			    // add scss entry points from
			    'src/scss/base.scss': 'style/base.css',
		    },
	    })
	    .build();

I'm getting 

    TypeError: metalsmith.match is not a function
        at @metalsmith/sass (/home/user/Documents/project/node_modules/@metalsmith/sass/lib/index.js:67:8)

**Comment by webketje** [comment]
@depuits can you paste your package.json `devDependencies` or `dependencies`? Normally if metalsmith-sugar passes metalsmith to the plugin (as is standard) it should work. `metalsmith.match` was added in `^2.4.1` (so maybe you can solve it simply by doing `npm i metalsmith@latest`. This was semver-wise a non-breaking change but apparently NPM doesn't output a peerDependency warning, so I'll leave this issue open as a request to throw an error notifying the user they should update to ms >= 2.4.1 (which is fully backwards-compatible). Thx!

**Comment by depuits** [comment]
This is the dependency list

```
  "devDependencies": {
    "@metalsmith/drafts": "^1.1.1",
    "@metalsmith/markdown": "^1.4.0",
    "@metalsmith/permalinks": "^2.4.0",
    "@metalsmith/sass": "^1.0.0",
    "bulma": "^0.9.3",
    "jstransformer-handlebars": "^1.2.0",
    "metalsmith": "^2.4.2",
    "metalsmith-assets-improved": "^1.0.1",
    "metalsmith-collections": "^0.9.0",
    "metalsmith-debug": "^1.2.0",
    "metalsmith-discover-helpers": "^0.1.1",
    "metalsmith-discover-partials": "^0.1.2",
    "metalsmith-excerpts": "^1.4.1",
    "metalsmith-handlebars-x": "^0.3.0",
    "metalsmith-in-place": "^4.4.2",
    "metalsmith-layouts": "^2.3.1",
    "metalsmith-linkcheck": "^0.3.4",
    "metalsmith-register-helpers": "^0.4.1",
    "metalsmith-rootpath": "^1.0.4",
    "metalsmith-sugar": "^1.1.0"
  }
```

So the metalsmith version is at `^2.4.2`. I do only get this error using sugar and running it without sugar does work. It might be a `metalsmith-sugar` problem but I thought I try asking here first because I couldn't see any activity over there and this is the only plugin which is not working.

**Comment by webketje** [comment]
@depuits It's a metalsmith-sugar issue, see its [package.json](https://github.com/connected-world-services/metalsmith-sugar/blob/master/package.json): it includes metalsmith^2.3.0 as a dependency (so by default ms-sugar uses a different version of ms than the one you have locally installed!). The author provides an escape hatch: `require("metalsmith-sugar")({  metalsmith: require("metalsmith") })`, although I would encourage him to change it to a `peerDependency`, which would be more flexible and make his pkg lighter

**Comment by depuits** [comment]
Thanks that does fix the issue. I've created an issue in the metalsmith-sugar repo to change the dependency.
